Adjust maximum argument length for illumos
sharkdp/argmax pull request #12
Opened 2023-03-26 11:08 UTC by citrus-it

While using `rustfd`'s `-X` option on an illumos system with a long list of files, I see:

```
% fd -t f . proto -X strings -a  | grep ':.*amd64' | sort
[fd error]: Problem while executing command: Arg list too long (os error 7)
```

This turns out to be because `strings` is a 32-bit program, which has a lower argument length limit than a 64-bit one.

Running this crate's tests on illumos fails:

```
test unix::tests::available_argument_length_is_smaller_than_experimental_limit ... FAILED

failures:

---- unix::tests::available_argument_length_is_smaller_than_experimental_limit stdout ----
Experimental limit: 1570369
thread 'unix::tests::available_argument_length_is_smaller_than_experimental_limit' panicked at 'assertion failed: available_argument_length([OsStr::new(\"echo\")].iter()).unwrap_or(0) <=\n    experimental_size_limit', src/unix.rs:110:9
```

sysconfig(ARG_MAX) is 2096640 for a 64-bit process and 1048320 for 32-bit.
Also defined in `<limits.h>`
```

The experimental limit using `/usr/bin/echo` (32-bit) is 1570369
The experimental limit using `/usr/bin/amd64/echo` (64-bit) is 2095129

I do not know a good way to retrieve the 32-bit

2023-03-27 15:42 UTC, tavianator requested changes
I checked how Illumos's `xargs` [handles this](https://github.com/illumos/illumos-gate/blob/af2e290bb42516a18ceaf6aed43dd7e45c108b08/usr/src/cmd/xargs/xargs.c#L69), and...

```c
#define	MAXARGS 255
```

which seems a little pessimistic :)

So I think this is a fine approach, I just have the one comment.

2023-03-27 15:42 UTC, tavianator commented on src/unix.rs
> +    if cfg!(target_os = "illumos") {
Can we limit this change to `target_pointer_width = 64`?

2023-03-28 12:40 UTC, citrus-it commented
> I checked how Illumos's `xargs` [handles this](https://github.com/illumos/illumos-gate/blob/af2e290bb42516a18ceaf6aed43dd7e45c108b08/usr/src/cmd/xargs/xargs.c#L69), and...
> 
> ```c
> #define	MAXARGS 255
> ```
> 
> which seems a little pessimistic :)

Yes, and https://github.com/illumos/illumos-gate/blob/master/usr/src/cmd/find/find.c#L77 uses `253`, both of which are too small.

> So I think this is a fine approach, I just have the one comment.

Done, thanks.

2023-03-28 14:55 UTC, tavianator approved these changes

2023-03-28 15:50 UTC, citrus-it commented
That particular example seems ok:

```
bloody% uname -a
SunOS bloody 5.11 omnios-master-69de2a5279f i86pc i386 i86pc
bloody% ./noshebang.sh $(yes | head -n256)
y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y
bloody% ./noshebang.sh $(yes | head -n512)
y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y
bloody%
bloody% head -1 noshebang.sh
# No shebang line
```

```
10455:  execve("./noshebang.sh", 0xFFFFFC7FEF010030, 0x01448A08) Err#8 ENOEXEC
10455:  execve("/bin/sh", 0xFFFFFC7FEF010028, 0x01448A08)  argc = 514
```

It seems like this might be worth delving more into though, thanks!

2023-03-28 16:12 UTC, tavianator commented
Ah, well I see that Illumos's `sh` [handles ENOEXEC itself](https://github.com/illumos/illumos-gate/blob/af2e290bb42516a18ceaf6aed43dd7e45c108b08/usr/src/cmd/sh/service.c#L264), and probably other shells do too.  If you force something to actually `execvp()` I think you'll see the error, maybe `nice ./noshebang.sh ...` or `nohup ...` will reproduce it.

2023-04-12 18:15 UTC, sharkdp commented
I haven't followed the full discussion (but I can catch up if needed). What is the current state of this PR?

2023-04-12 19:17 UTC, tavianator commented
It looks fine to me!

2023-04-12 19:36 UTC, merged